version: '3.9'

services:
  app_zookeeper:
    image: wurstmeister/zookeeper:latest
    network_mode: "host"
    restart: unless-stopped

  app_kafka:
    image: wurstmeister/kafka:latest
    network_mode: "host"
    environment:
      HOSTNAME_COMMAND: echo "$$(hostname).rtb-lab.pl"
      KAFKA_ZOOKEEPER_CONNECT: 10.112.105.107:2181
      KAFKA_CREATE_TOPICS: user_tags:3:2
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

