---
- name: Aerospike install
  hosts: aerospike

  tasks:
     - name: Download Aerospike Community Version installation package 
       become: true
       become_user: st105
       ansible.builtin.get_url:
             url: https://download.aerospike.com/download/server/latest/artifact/ubuntu20
             dest: /tmp/aerospike.tar.gz
     
     - name: Extract installation package 
       become: true
       become_user: st105
       ansible.builtin.command:
              argv:
                - tar
                - xzvf
                - aerospike.tar.gz
              chdir: /tmp/

     - name: Install server 
       become: true
       become_user: root 
       ansible.builtin.command:
              argv:
                - ./asinstall
              chdir: /tmp/aerospike-server-community-6.1.0.1-ubuntu20.04/

     - name: Create logging directory
       become: true
       become_user: root
       ansible.builtin.file:
              path: /var/log/aerospike 
              state: directory

     - name: Copy config file 
       become: true
       become_user: root
       register: service_conf
       ansible.builtin.copy:
             src: ../app_aerospike/aerospike.conf
             dest: /etc/aerospike/aerospike.conf
             #owner: root
             #group: root
             #mode: '0644'

     - name: Ensure the aerospike server is running
       become: true
       become_user: root
       ansible.builtin.systemd:
             name: aerospike 
             state: started
             enabled: yes
             daemon_reload: yes

     - name: Restart server on config change
       become: true
       become_user: root
       ansible.builtin.systemd:
             name: aerospike 
             state: restarted
       when: service_conf.changed

