---
- name: Docker install
  hosts: all 

  tasks:
     - name: Install the latest version of Docker
       become: true
       become_user: root
       yum:
             name: docker.io
             state: latest

     - name: Create directory
       become: true
       ansible.builtin.file:
              path: /etc/systemd/system/docker.service.d
              state: directory

     - name: Copy docker service file with owner and permissions
       become: true
       register: service_conf
       ansible.builtin.copy:
             src: docker.service
             dest: /etc/systemd/system/docker.service.d/override.conf
             owner: root
             group: root
             mode: '0644'

     - name: Ensure the docker daemon is enabled
       become: true
       become_user: root
       systemd:
             name: docker
             state: started
             enabled: yes
             daemon_reload: yes

     - name: Restart daemon on config change
       become: true
       become_user: root
       systemd:
             name: docker
             state: restarted
       when: service_conf.changed

     - name: Get uname -s
       become: true
       shell: uname -s 
       register: uname_s

     - name: Get uname -m
       become: true
       shell: uname -m
       register: uname_m

     - name: Download newest docker-compose 
       become: true
       ansible.builtin.get_url:
             url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{uname_s.stdout}}-{{uname_m.stdout}}
             dest: /usr/local/bin/docker-compose
     
     - name: Make docker-compose executable 
       become: true
       become_user: root
       ansible.builtin.file:
              path: /usr/local/bin/docker-compose
              attr: "+x"
     
     - name: Add path update to .bashrc 
       lineinfile:
              path: ~/.bashrc
              search_string: "export PATH=~/usr/local/bin:$PATH"
              state: present

