---
- name: Stop and clean all containers 
  hosts: all

  tasks:
     - name: docker stop 
       become: true
       become_user: root
       shell: docker stop $(docker ps -a -q) 

     - name: docker rm
       become: true
       become_user: root
       command:
          argv:
            - docker
            - rm
            - $(docker ps -a -q) 
