---
- name: Stop and clean all containers 
  hosts: all

  tasks:
     - name: get containers
       become: true
       become_user: root
       shell: docker ps -q 
       register: containers

     - name: docker stop 
       become: true
       become_user: root
       shell: docker stop "{{ item }}"
       with_items: "{{ containers.stdout_lines }}"

     - name: docker rm
       become: true
       become_user: root
       shell: docker rm "{{ item }}"
       with_items: "{{ containers.stdout_lines }}"
