---
- name: Stop and clean all containers 
  hosts: all_hosts

  tasks:
     - name: get containers
       become: true
       become_user: root
       shell: docker ps -a -q 
       register: containers

     - name: docker stop 
       become: true
       become_user: root
       shell: docker stop {{ containers.stdout | regex_replace('\n', ' ') }}
       ignore_errors: yes

     - name: docker container prune 
       become: true
       become_user: root
       shell: docker container prune -f
